// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package sumermcu_uart_reg_pkg;

    localparam SUMERMCU_UART_REG_DATA_WIDTH = 32;
    localparam SUMERMCU_UART_REG_MIN_ADDR_WIDTH = 5;
    localparam SUMERMCU_UART_REG_SIZE = 'h14;

    typedef struct {
        logic [7:0] next;
    } sumermcu_uart_reg__UART_RDR__rx_data__in_t;

    typedef struct {
        sumermcu_uart_reg__UART_RDR__rx_data__in_t rx_data;
    } sumermcu_uart_reg__UART_RDR__in_t;

    typedef struct {
        logic next;
    } sumermcu_uart_reg__UART_CFG__rx_ready__in_t;

    typedef struct {
        logic next;
    } sumermcu_uart_reg__UART_CFG__tx_done__in_t;

    typedef struct {
        sumermcu_uart_reg__UART_CFG__rx_ready__in_t rx_ready;
        sumermcu_uart_reg__UART_CFG__tx_done__in_t tx_done;
    } sumermcu_uart_reg__UART_CFG__in_t;

    typedef struct {
        sumermcu_uart_reg__UART_RDR__in_t RDR;
        sumermcu_uart_reg__UART_CFG__in_t CFG;
    } sumermcu_uart_reg__in_t;

    typedef struct {
        logic [31:0] value;
    } sumermcu_uart_reg__UART_CPB__cpb_value__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_CPB__cpb_value__out_t cpb_value;
    } sumermcu_uart_reg__UART_CPB__out_t;

    typedef struct {
        logic [31:0] value;
    } sumermcu_uart_reg__UART_STP__stop_bits__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_STP__stop_bits__out_t stop_bits;
    } sumermcu_uart_reg__UART_STP__out_t;

    typedef struct {
        logic [7:0] value;
    } sumermcu_uart_reg__UART_RDR__rx_data__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_RDR__rx_data__out_t rx_data;
    } sumermcu_uart_reg__UART_RDR__out_t;

    typedef struct {
        logic [7:0] value;
    } sumermcu_uart_reg__UART_TDR__tx_data__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_TDR__tx_data__out_t tx_data;
    } sumermcu_uart_reg__UART_TDR__out_t;

    typedef struct {
        logic value;
    } sumermcu_uart_reg__UART_CFG__tx_en__out_t;

    typedef struct {
        logic value;
    } sumermcu_uart_reg__UART_CFG__rx_ready__out_t;

    typedef struct {
        logic value;
        logic swmod;
    } sumermcu_uart_reg__UART_CFG__tx_done__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_CFG__tx_en__out_t tx_en;
        sumermcu_uart_reg__UART_CFG__rx_ready__out_t rx_ready;
        sumermcu_uart_reg__UART_CFG__tx_done__out_t tx_done;
    } sumermcu_uart_reg__UART_CFG__out_t;

    typedef struct {
        sumermcu_uart_reg__UART_CPB__out_t CPB;
        sumermcu_uart_reg__UART_STP__out_t STP;
        sumermcu_uart_reg__UART_RDR__out_t RDR;
        sumermcu_uart_reg__UART_TDR__out_t TDR;
        sumermcu_uart_reg__UART_CFG__out_t CFG;
    } sumermcu_uart_reg__out_t;
endpackage
