// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package uart_regblock_pkg;

    localparam UART_REGBLOCK_DATA_WIDTH = 32;
    localparam UART_REGBLOCK_MIN_ADDR_WIDTH = 5;
    localparam UART_REGBLOCK_SIZE = 'h14;

    typedef struct {
        logic [7:0] next;
    } uart_regblock__UART_RDR__rx_data__in_t;

    typedef struct {
        uart_regblock__UART_RDR__rx_data__in_t rx_data;
    } uart_regblock__UART_RDR__in_t;

    typedef struct {
        logic next;
    } uart_regblock__UART_CFG__rx_ready__in_t;

    typedef struct {
        logic next;
    } uart_regblock__UART_CFG__tx_done__in_t;

    typedef struct {
        uart_regblock__UART_CFG__rx_ready__in_t rx_ready;
        uart_regblock__UART_CFG__tx_done__in_t tx_done;
    } uart_regblock__UART_CFG__in_t;

    typedef struct {
        uart_regblock__UART_RDR__in_t RDR;
        uart_regblock__UART_CFG__in_t CFG;
    } uart_regblock__in_t;

    typedef struct {
        logic [31:0] value;
    } uart_regblock__UART_CPB__cpb_value__out_t;

    typedef struct {
        uart_regblock__UART_CPB__cpb_value__out_t cpb_value;
    } uart_regblock__UART_CPB__out_t;

    typedef struct {
        logic [31:0] value;
    } uart_regblock__UART_STP__stop_bits__out_t;

    typedef struct {
        uart_regblock__UART_STP__stop_bits__out_t stop_bits;
    } uart_regblock__UART_STP__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_regblock__UART_RDR__rx_data__out_t;

    typedef struct {
        uart_regblock__UART_RDR__rx_data__out_t rx_data;
    } uart_regblock__UART_RDR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_regblock__UART_TDR__tx_data__out_t;

    typedef struct {
        uart_regblock__UART_TDR__tx_data__out_t tx_data;
    } uart_regblock__UART_TDR__out_t;

    typedef struct {
        logic value;
    } uart_regblock__UART_CFG__tx_en__out_t;

    typedef struct {
        logic value;
    } uart_regblock__UART_CFG__rx_ready__out_t;

    typedef struct {
        logic value;
        logic swmod;
    } uart_regblock__UART_CFG__tx_done__out_t;

    typedef struct {
        uart_regblock__UART_CFG__tx_en__out_t tx_en;
        uart_regblock__UART_CFG__rx_ready__out_t rx_ready;
        uart_regblock__UART_CFG__tx_done__out_t tx_done;
    } uart_regblock__UART_CFG__out_t;

    typedef struct {
        uart_regblock__UART_CPB__out_t CPB;
        uart_regblock__UART_STP__out_t STP;
        uart_regblock__UART_RDR__out_t RDR;
        uart_regblock__UART_TDR__out_t TDR;
        uart_regblock__UART_CFG__out_t CFG;
    } uart_regblock__out_t;
endpackage
